# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52668908dd48d3961078b0ed45bb5ecc91696181cfb725e5d04dfef65174f11586876fe8d5e1d9926033ffc2bb666f53a02a3b02276e6bf05120b1a505bd3802

test:
  secret_key_base: a9c8547f8c3d59a69608b51c7ffb7c6a850a3a37f9f3ba7fef4e782ea8488f95c9738ef7d7226985ed9aa23ed533ec1960bf67443dd8ac146b2cf583f2cd2b51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
